# ----------------------------
# Makefile Options
# ----------------------------

NAME = edge
DESCRIPTION = "Bitmap at edges test"
COMPRESSED = NO
LDHAS_ARG_PROCESSING = 1

CFLAGS = -Wall -Wextra -Oz
CXXFLAGS = -Wall -Wextra -Oz

# ----------------------------

include $(shell cedev-config --makefile)
