# ----------------------------
# Makefile Options
# ----------------------------

NAME = parse
DESCRIPTION = "parse a csc type file
COMPRESSED = NO
LDHAS_ARG_PROCESSING = 1

CFLAGS = -Wall -Wextra -Oz
CXXFLAGS = -Wall -Wextra -Oz

# ----------------------------

include $(shell cedev-config --makefile)

