# ----------------------------
# Makefile Options
# ----------------------------

NAME = arr
DESCRIPTION = "Ag C array alloc demo"
COMPRESSED = NO

CFLAGS = -Wall -Wextra -Oz
CXXFLAGS = -Wall -Wextra -Oz

BSSHEAP_LOW = 050000
BSSHEAP_HIGH = 0AFFFF

# ----------------------------

include $(shell cedev-config --makefile)
