# ----------------------------
# Makefile Options
# ----------------------------

NAME = arr
DESCRIPTION = "Ag C array alloc demo"
COMPRESSED = NO

CFLAGS = -Wall -Wextra -Oz
CXXFLAGS = -Wall -Wextra -Oz

# ----------------------------

include $(shell cedev-config --makefile)
