# ----------------------------
# Makefile Options
# ----------------------------

NAME = wfc
DESCRIPTION = "Wave Function Collapse expt"
COMPRESSED = NO
LDHAS_ARG_PROCESSING = 1

CFLAGS = -Wall -Wextra -Oz
CXXFLAGS = -Wall -Wextra -Oz

# ----------------------------

include $(shell cedev-config --makefile)
